[x1,Fs1] = audioread('author.wav')
[x2,Fs2] = audioread('authorflanger.wav')

l1 = length(x1)
l2 = length(x2)

subplot(2,1,1)
plot(x1)
xlim([0 l1])
title('output from the filter implemented with direct form')
subplot(2,1,2)
plot(x2)
xlim([0 l2])
title('output from the filter implemented with canonical form')
% subplot(3,1,3)
% plot(x1-x2)
% xlim([0 l1])
% title('difference between two waveforms')
% suptitle('Verification of consistency of two implementation ways')